### ISSUE TITLE
tracking issue for players table related tasks

### ISSUE THREAD

**Issue by mistakia** [mistakia/league#147]
# players table related tasks

- [ ] allow calculating play by play stats from any subset of plays (season, week, opponent, down, distance, etc... any play by play column)
- [ ] metrics to add/include
  - [ ] betting market props
    - [ ] season futures
    - [ ] weekly props
  - [ ] espn open source metrics
  - [ ] ngs prospect grade
  - [ ] ras score
  - [ ] bmi
  - [ ] rookie age
  - [ ] nfl draft grade (z-score)
  - [ ] pff grades
  - [ ] fantasy stats
    - [ ] ppg
    - [ ] ppg_rank
    - [ ] xppg
    - [ ] xppg_rank
    - [ ] pts+
    - [ ] pts+_rank
