### ISSUE TITLE
tracking issue for implementing robust team "market value" based on market/trade demand for team assets

### ISSUE THREAD

**Issue by mistakia** [mistakia/league#219]
- [ ] adjustments for league format (salary, scoring, etc)
- [ ] ingest trades from leagues, index based on league format
- [ ] document how the calculation is made
