### ISSUE TITLE
feat: tracking issue for league specific trade analysis

### ISSUE THREAD

**Issue by mistakia** [mistakia/league#240]
**Tasks**
- [x] projected Points analysis
- [x] overall value analysis (player + draft)
- [x] player value analysis
- [x] draft value analysis
- [x] value adjustments for salary cap
- [x] salary cap analysis
- [x] league specific draft capital valuations

All of these calculations need to be documented and audited. 

**Current Design**
<img width="963" alt="Screen Shot 2024-09-01 at 10 19 23 AM" src="https://github.com/user-attachments/assets/b67d8a13-400f-4ac5-aaaf-b6a3c4303461">
