### ISSUE TITLE
tracking issue Improve View Presets

### ISSUE THREAD

**Issue by CPLANT14** [mistakia/league#258]
- [ ]  When adding New View make the edit view name & description automatically pop-up
- [ ] Add Folders to organize view presets
- [ ] Find way to preview view presets outside of descriptions
- [ ] Add Favorites button to add a view to your favorites for quick and easy access
