### ISSUE TITLE
Tracking Issue: Improvement on Projections

### ISSUE THREAD

**Issue by CPLANT14** [mistakia/league#261]
- [ ] https://github.com/mistakia/league/issues/189
- [ ] Support other scoring settings (Mainly PPR)
- [ ] Add Dynamic Parameters to projections, (Next 3 or Last 3)
- [ ] Week Parameter for Projections
- [ ] Select Sources included for projections
